var express = require('express');
var router = express.Router();

router.get('/', function(req, res, next) {
  //res.render('index', { title: 'Express' });
  res.json({ "success": true });
});

router.get('/location-test', function(req, res, next) {
  res.json([
 {
   "FIELD1": 1,
   "ID": "A1025181",
   "PREMIUM": 1293,
   "TIV": 168149,
   "BLDG_LIMIT": 170001,
   "DED": 1000,
   "POSTALCODE": 29607,
   "CITY": "GREENVILLE",
   "DISTRICT": "",
   "COUNTYCODE": 45,
   "COUNTY": "GREENVILLE COUNTY",
   "STATECODE": "SC",
   "STATE": "SOUTH CAROLINA",
   "CRESTA": "",
   "SUBCRESTA": null,
   "COUNTRY": "US",
   "LATITUDE": 34.845617,
   "LONGITUDE": -82.364463,
   "ADDRMATCH": 2,
   "NUMBLDGS": 1,
   "BLDGSCHEME": "RMS",
   "BLDGCLASS": "1",
   "OCCSCHEME": "ATC",
   "OCCTYPE": 1,
   "NUMSTORIES": 1,
   "YEARBUILT": 1950,
   "ELEVATION": 980.0300293,
   "DISTCOAST": 194.0998688,
   "WINDPOOL": 0,
   "NFIP_RATE": 0,
   "NFIPYEAR": 1975,
   "ROOFSYS": 0,
   "ROOFGEOM": 0,
   "ROOFANCH": 0,
   "ROOFAGE": 0,
   "CLADSYS": 0,
   "FRAMEBOLT": "",
   "CLADDING": "",
   "EQSLINS": "",
   "LANDSLIDE": "",
   "LANDCOV": "",
   "LIQUEFACT": "",
   "LIQUECOV": "",
   "SOILTYPE": "",
   "SOILCOV": "",
   "SOILPERIOD": "",
   "SOILTHICKNESS": ""
 },
 {
   "FIELD1": 2,
   "ID": "F102520",
   "PREMIUM": 8441,
   "TIV": 1110297,
   "BLDG_LIMIT": 1110297,
   "DED": 25324,
   "POSTALCODE": 34113,
   "CITY": "NAPLES",
   "DISTRICT": "",
   "COUNTYCODE": 21,
   "COUNTY": "COLLIER COUNTY",
   "STATECODE": "FL",
   "STATE": "FLORIDA",
   "CRESTA": "",
   "SUBCRESTA": null,
   "COUNTRY": "US",
   "LATITUDE": 26.074383,
   "LONGITUDE": -81.703689,
   "ADDRMATCH": 2,
   "NUMBLDGS": 1,
   "BLDGSCHEME": "RMS",
   "BLDGCLASS": "2",
   "OCCSCHEME": "ATC",
   "OCCTYPE": 2,
   "NUMSTORIES": 2,
   "YEARBUILT": 1997,
   "ELEVATION": 6.092000008,
   "DISTCOAST": 5.126898425,
   "WINDPOOL": 0,
   "NFIP_RATE": 0.600000024,
   "NFIPYEAR": 1975,
   "ROOFSYS": 5,
   "ROOFGEOM": 4,
   "ROOFANCH": 3,
   "ROOFAGE": 1,
   "CLADSYS": 5,
   "FRAMEBOLT": "",
   "CLADDING": "",
   "EQSLINS": "",
   "LANDSLIDE": "",
   "LANDCOV": "",
   "LIQUEFACT": "",
   "LIQUECOV": "",
   "SOILTYPE": "",
   "SOILCOV": "",
   "SOILPERIOD": "",
   "SOILTHICKNESS": ""
 },
 {
   "FIELD1": 3,
   "ID": "A1025291",
   "PREMIUM": 450,
   "TIV": 122650,
   "BLDG_LIMIT": 59188,
   "DED": 1000,
   "POSTALCODE": 38635,
   "CITY": "HOLLY SPRINGS",
   "DISTRICT": "",
   "COUNTYCODE": 93,
   "COUNTY": "MARSHALL COUNTY",
   "STATECODE": "MS",
   "STATE": "MISSISSIPPI",
   "CRESTA": "",
   "SUBCRESTA": 32820,
   "COUNTRY": "US",
   "LATITUDE": 34.73294,
   "LONGITUDE": -89.54712,
   "ADDRMATCH": 2,
   "NUMBLDGS": 1,
   "BLDGSCHEME": "RMS",
   "BLDGCLASS": "3",
   "OCCSCHEME": "ATC",
   "OCCTYPE": 1,
   "NUMSTORIES": 1,
   "YEARBUILT": 1976,
   "ELEVATION": 536.539978,
   "DISTCOAST": 294.0838013,
   "WINDPOOL": 0,
   "NFIP_RATE": 0,
   "NFIPYEAR": 1975,
   "ROOFSYS": 0,
   "ROOFGEOM": 0,
   "ROOFANCH": 0,
   "ROOFAGE": 0,
   "CLADSYS": 0,
   "FRAMEBOLT": "",
   "CLADDING": "",
   "EQSLINS": "",
   "LANDSLIDE": "",
   "LANDCOV": "",
   "LIQUEFACT": "",
   "LIQUECOV": "",
   "SOILTYPE": "",
   "SOILCOV": "",
   "SOILPERIOD": "",
   "SOILTHICKNESS": ""
 },
 {
   "FIELD1": 6,
   "ID": "B102551",
   "PREMIUM": 250,
   "TIV": 19545,
   "BLDG_LIMIT": 19545,
   "DED": 297,
   "POSTALCODE": 34747,
   "CITY": "KISSIMMEE",
   "DISTRICT": "",
   "COUNTYCODE": 97,
   "COUNTY": "OSCEOLA COUNTY",
   "STATECODE": "FL",
   "STATE": "FLORIDA",
   "CRESTA": "",
   "SUBCRESTA": 36740,
   "COUNTRY": "US",
   "LATITUDE": 28.34064,
   "LONGITUDE": -81.64506,
   "ADDRMATCH": 2,
   "NUMBLDGS": 1,
   "BLDGSCHEME": "RMS",
   "BLDGCLASS": "4B1",
   "OCCSCHEME": "ATC",
   "OCCTYPE": 2,
   "NUMSTORIES": 1,
   "YEARBUILT": 2000,
   "ELEVATION": 109.5999985,
   "DISTCOAST": 52.82582855,
   "WINDPOOL": 0,
   "NFIP_RATE": 0,
   "NFIPYEAR": 1975,
   "ROOFSYS": 2,
   "ROOFGEOM": 2,
   "ROOFANCH": 3,
   "ROOFAGE": 3,
   "CLADSYS": 0,
   "FRAMEBOLT": "",
   "CLADDING": "",
   "EQSLINS": "",
   "LANDSLIDE": "",
   "LANDCOV": "",
   "LIQUEFACT": "",
   "LIQUECOV": "",
   "SOILTYPE": "",
   "SOILCOV": "",
   "SOILPERIOD": "",
   "SOILTHICKNESS": ""
 },
 {
   "FIELD1": 7,
   "ID": "B102557",
   "PREMIUM": 703,
   "TIV": 92495,
   "BLDG_LIMIT": 92495,
   "DED": 1406,
   "POSTALCODE": 34747,
   "CITY": "KISSIMMEE",
   "DISTRICT": "",
   "COUNTYCODE": 97,
   "COUNTY": "OSCEOLA COUNTY",
   "STATECODE": "FL",
   "STATE": "FLORIDA",
   "CRESTA": "",
   "SUBCRESTA": 36740,
   "COUNTRY": "US",
   "LATITUDE": 28.34064,
   "LONGITUDE": -81.64506,
   "ADDRMATCH": 2,
   "NUMBLDGS": 1,
   "BLDGSCHEME": "RMS",
   "BLDGCLASS": "1",
   "OCCSCHEME": "ATC",
   "OCCTYPE": 2,
   "NUMSTORIES": 1,
   "YEARBUILT": 2000,
   "ELEVATION": 109.5999985,
   "DISTCOAST": 52.82582855,
   "WINDPOOL": 0,
   "NFIP_RATE": 0,
   "NFIPYEAR": 1975,
   "ROOFSYS": 5,
   "ROOFGEOM": 4,
   "ROOFANCH": 3,
   "ROOFAGE": 3,
   "CLADSYS": 5,
   "FRAMEBOLT": "",
   "CLADDING": "",
   "EQSLINS": "",
   "LANDSLIDE": "",
   "LANDCOV": "",
   "LIQUEFACT": "",
   "LIQUECOV": "",
   "SOILTYPE": "",
   "SOILCOV": "",
   "SOILPERIOD": "",
   "SOILTHICKNESS": ""
 }
])
});

module.exports = router;
